policy:
  approval:
    - or:
        - and:
            - tests passed
            - developer-platform has approved
        - and:
            - dependabot is making the PR
            - or:
                - tests passed
                - developer-platform has approved
  disapproval:
    requires:
      organizations:
        - "bestseller"
approval_rules:
  - name: tests passed
    requires:
      conditions:
        has_workflow_result:
          workflows:
            - ".github/workflows/build.yml"
            - ".github/workflows/test.yml"
  - name: developer-platform has approved
    requires:
      count: 1
      teams:
        - "BESTSELLER/developer-platform"
  - name: dependabot is making the PR
    requires:
      count: 0
      conditions:
        has_author_in:
          users:
            - "dependabot[bot]"
