policy:
  approval:
    - or:
        - and:
            - tests passed
            - developer-platform has approved
        - and:
            - dependabot is making the PR
            - or:
                - tests passed
                - developer-platform has approved
  disapproval:
    requires:
      organizations:
        - "bestseller"
approval_rules:
  - name: tests passed
    if:
      has_workflow_result:
        workflows:
          - ".github/workflows/build_deploy.yml"
          - ".github/workflows/test.yml"
    requires:
      count: 0
  - name: developer-platform has approved
    requires:
      count: 1
      teams:
        - "BESTSELLER/developer-platform"
  - name: dependabot is making the PR
    if:
      has_author_in:
        users:
          - "dependabot[bot]"
    requires:
      count: 0
