version: 2.1
executors:
  go_image:
    docker:
      - image: circleci/golang:1.15

orbs:
  secret-injector: bestsellerit/secret-injector@0.2.34

jobs:
  test:
    executor: go_image
    working_directory: /go/src/github.com/BESTSELLER/harpocrates
    steps:
      - checkout
      - run:
          name: download dependencies
          command: GO111MODULE=on CGO_ENABLED=0 go mod vendor
      - run:
          name: go get
          command: |
            go get ./...
      - run:
          name: go build
          command: |
            go build -ldflags="-s -w"
            ls -l harpocrates
      - run:
          name: go test - sonar
          command: |
            echo -n > /tmp/report.json
            go test ./... -coverprofile=coverage.out -json harpocrates >> /tmp/report.json
      - store_test_results:
          path: /tmp/report.json
      - persist_to_workspace:
          root: /tmp
          paths:
            - report.json

  test-sonar:
    executor: go_image
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Install Sonarqube scanner
          command: |
            SONAR_VERSION=4.2.0.1873-linux
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_VERSION.zip -P /tmp/
            cd /tmp
            unzip /tmp/sonar-scanner-cli-$SONAR_VERSION.zip
            mv /tmp/sonar-scanner-$SONAR_VERSION /tmp/sonar-scanner
      - run:
          name: Run SonarCloud Scanner
          command: |
            source /tmp/secrets.env
            export SONAR_SCANNER_OPTS="-Xmx2048m"
            eval /tmp/sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=$K8S_CLUSTER_SONAR_ORG"_"$CIRCLE_PROJECT_REPONAME \
              -Dsonar.projectName=$CIRCLE_PROJECT_REPONAME \
              -Dsonar.organization=$K8S_CLUSTER_SONAR_ORG \
              -Dsonar.sources=. \
              -Dsonar.test.inclusions=**/**_test.go \
              -Dsonar.sources.inclusions=**/**.go \
              -Dsonar.host.url=$K8S_CLUSTER_SONAR_HOST \
              -Dsonar.login=$K8S_CLUSTER_SONAR_LOGIN \
              -Dsonar.links.scm=$CIRCLE_REPOSITORY_URL \
              -Dsonar.go.coverage.reportPaths=/tmp/report.json

  build-go:
    executor: go_image
    working_directory: /go/src/github.com/BESTSELLER/harpocrates
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: go build - windows/amd64
          command: |
            GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o harpocrates.exe
            tar -czvf /tmp/harpocrates_$CIRCLE_TAG\_windows_amd64.tar.gz harpocrates.exe
            rm harpocrates.exe
      - run:
          name: go build - darwin/amd64
          command: |
            GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o harpocrates
            tar -czvf /tmp/harpocrates_$CIRCLE_TAG\_darwin_amd64.tar.gz harpocrates
            rm harpocrates
      - run:
          name: go build - linux/amd64
          command: |
            GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o harpocrates
            tar -czvf /tmp/harpocrates_$CIRCLE_TAG\_linux_amd64.tar.gz harpocrates
            mv harpocrates /tmp
      - persist_to_workspace:
          root: /tmp
          paths:
            - harpocrates*
  build-docker:
    docker:
      - image: docker:18.06.3-ce-git
    working_directory: /app
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker
      - run:
          name: Push and build image
          command: |
            source /tmp/secrets.env
            cp /tmp/harpocrates .
            docker login -u $docker_harpocrates_username -p $docker_harpocrates_password $K8S_CLUSTER_docker_registry_url
            docker build \
              -t $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG \
              -t $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:latest \
              .
            docker push $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
            docker push $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:latest
  
  publish:
    executor: go_image
    working_directory: /go/src/github.com/BESTSELLER/harpocrates
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Install Vault and login
          command: |
            VERSION=1.2.3
            wget https://releases.hashicorp.com/vault/$VERSION/vault_$VERSION\_linux_amd64.zip
            sudo unzip -o vault_$VERSION\_linux_amd64.zip -d /usr/bin/
            sudo chmod +x /usr/bin/vault
            vault login -method=userpass username=$VAULT_USERNAME password=$VAULT_PASSWORD >/dev/null
      - run:
          name: Create release folder
          command: |
            mkdir releases
            cp /tmp/harpocrates_* ./releases
      - run:
          name: Update stuff with git tag
          command: |
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/CronJob.yml
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/Deployment.yml
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/orb.yml
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/StatefulSet.yml
            cp orb/CronJob.yml ./releases
            cp orb/Deployment.yml ./releases
            cp orb/StatefulSet.yml ./releases
            cp orb/kustomization.yml ./releases
      - run:
          name: Download ghr
          command: |
            GHR_VERSION=v0.13.0
            wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/$GHR_VERSION/ghr_$GHR_VERSION\_linux_386.tar.gz
            tar -xvzf ghr.tar.gz
            sudo mv ghr_$GHR_VERSION\_linux_386/ghr /usr/local/bin
      - run:
          name: Create Github releases
          command: |
            ghr -replace $CIRCLE_TAG ./releases
      - run:
          name: Publish CircleCI orb
          command: |
            wget https://github.com/CircleCI-Public/circleci-cli/releases/download/v0.1.5879/circleci-cli_0.1.5879_linux_amd64.tar.gz
            tar -xf circleci-cli_0.1.5879_linux_amd64.tar.gz
            mv circleci-cli_0.1.5879_linux_amd64 cli

            export CIRCLECI_CLI_TOKEN=$(vault kv get -field=circleci_token ES/harpocrates)
            CC_NAMESPACE=bestsellerit
            ORB_PATH=./orb/orb.yml
            ORB_NAME=secret-injector
            
            ./cli/circleci orb validate $ORB_PATH
            ./cli/circleci orb publish $ORB_PATH $CC_NAMESPACE/$ORB_NAME@$CIRCLE_TAG
            ./cli/circleci orb unlist $CC_NAMESPACE/$ORB_NAME true

workflows:
  test:
    jobs:
      - secret-injector/dump-secrets:
          vault-path: ES/service_accounts/harbor/harpocrates-ci
          # context: es03-prod
      - test
      - test-sonar:
          # context: es03-prod
          requires:
            - test
            - secret-injector/dump-secrets

  test-build:
    jobs:
      - secret-injector/dump-secrets:
          vault-path: ES/service_accounts/harbor/harpocrates-ci
          # context: es03-prod
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - test:
          filters:
              tags:
                only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
              branches:
                ignore: /.*/
      - test-sonar:
          # context: es03-prod
          requires:
            - test
            - secret-injector/dump-secrets
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - build-go:
          # context: es03-prod
          requires:
            - test-sonar
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - build-docker:
          # context: es03-prod
          requires:
            - build-go
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
      - publish:
          # context: es03-prod
          requires:
            - build-docker
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/
