version: 2.1
executors:
  go_image:
    docker:
      - image: cimg/go:1.16
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
  docker:
    docker:
      - image: docker:stable-git
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

orbs:
  secret-injector: bestsellerit/secret-injector@1.5.4

jobs:
  test:
    executor: go_image
    steps:
      - checkout
      - run:
          name: go get
          command: |
            go get ./...
      - run:
          name: install gotestsum
          command: |
            go get -u gotest.tools/gotestsum
            go get gotest.tools/assert@v2.2.0+incompatible
      - run:
          name: go test
          command: |
            mkdir junit
            gotestsum --junitfile junit/unit-tests.xml
      - store_test_results:
          path: ~/project/junit
      - run:
          name: go build
          command: |
            GOOS=linux \
            GOARCH=amd64 \
            go build -ldflags="-w -s"
  test-sonar:
    executor: go_image
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Install Sonarqube scanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip -P /tmp/
            cd /tmp/
            unzip sonar-scanner-cli-4.5.0.2216-linux.zip
      - run:
          name: go get
          command: |
            go get ./...
      - run:
          name: go test - sonar
          command: |
            go test ./... -coverprofile=coverage.out
      - run:
          name: Run SonarCloud Scanner
          command: |
            source /tmp/secrets
            export SONAR_SCANNER_OPTS="-Xmx2048m"
            eval /tmp/sonar-scanner-4.5.0.2216-linux/bin/sonar-scanner \
              -Dsonar.projectKey=$K8S_CLUSTER_SONAR_KEY_GH"_"$CIRCLE_PROJECT_REPONAME \
              -Dsonar.projectName=$CIRCLE_PROJECT_REPONAME \
              -Dsonar.organization=$K8S_CLUSTER_SONAR_ORG_GH \
              -Dsonar.sources=. \
              -Dsonar.test.inclusions=**/**_test.go \
              -Dsonar.sources.inclusions=**/**.go \
              -Dsonar.host.url=$K8S_CLUSTER_SONAR_HOST \
              -Dsonar.login=$K8S_CLUSTER_SONAR_LOGIN_GH \
              -Dsonar.links.scm=$CIRCLE_REPOSITORY_URL \
              -Dsonar.go.coverage.reportPaths=coverage.out

  build-go:
    executor: go_image
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: go build - windows/amd64
          command: |
            GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o harpocrates.exe
            tar -czvf /tmp/harpocrates_$CIRCLE_TAG\_windows_amd64.tar.gz harpocrates.exe
            rm harpocrates.exe
      - run:
          name: go build - darwin/amd64
          command: |
            GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o harpocrates
            tar -czvf /tmp/harpocrates_$CIRCLE_TAG\_darwin_amd64.tar.gz harpocrates
            rm harpocrates
      - run:
          name: go build - linux/amd64
          command: |
            GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o harpocrates
            tar -czvf /tmp/harpocrates_$CIRCLE_TAG\_linux_amd64.tar.gz harpocrates
            mv harpocrates /tmp
      - persist_to_workspace:
          root: /tmp
          paths:
            - harpocrates*
  docker-build-n-push:
    executor: docker
    working_directory: /app
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker
      - run:
          name: Push and build image
          command: |
            source /tmp/secrets
            cp /tmp/harpocrates .
            docker login -u $docker_harpocrates_username -p $docker_harpocrates_password $K8S_CLUSTER_docker_registry_url
            docker build \
              -t $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG \
              -t $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:latest \
              .
            docker push $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
            docker push $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:latest
  docker-build:
    executor: docker
    working_directory: /app
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - setup_remote_docker
      - run:
          name: Push and build image
          command: |
            source /tmp/secrets
            cp /tmp/harpocrates .
            docker login -u $docker_harpocrates_username -p $docker_harpocrates_password $K8S_CLUSTER_docker_registry_url
            docker build \
              -t $K8S_CLUSTER_docker_registry_url/library/$CIRCLE_PROJECT_REPONAME:latest \
              .

  publish:
    executor: go_image
    steps:
      - attach_workspace:
          at: /tmp
      - checkout
      - run:
          name: Install Vault and login
          command: |
            VERSION=1.6.1
            wget https://releases.hashicorp.com/vault/$VERSION/vault_$VERSION\_linux_amd64.zip
            sudo unzip -o vault_$VERSION\_linux_amd64.zip -d /usr/bin/
            sudo chmod +x /usr/bin/vault
            vault login -method=userpass username=$VAULT_USERNAME password=$VAULT_PASSWORD >/dev/null
      - run:
          name: Create release folder
          command: |
            mkdir releases
            cp /tmp/harpocrates_* ./releases
      - run:
          name: Update stuff with git tag
          command: |
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/CronJob.yml
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/Deployment.yml
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/orb.yml
            sed -i -e "s?\$HARPOCRATES_VERSION?$CIRCLE_TAG?g" orb/StatefulSet.yml
            cp orb/CronJob.yml ./releases
            cp orb/Deployment.yml ./releases
            cp orb/StatefulSet.yml ./releases
            cp orb/kustomization.yml ./releases
      - run:
          name: Download ghr
          command: |
            GHR_VERSION=v0.13.0
            wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/$GHR_VERSION/ghr_$GHR_VERSION\_linux_386.tar.gz
            tar -xvzf ghr.tar.gz
            sudo mv ghr_$GHR_VERSION\_linux_386/ghr /usr/local/bin
      - run:
          name: Create Github releases
          command: |
            ghr -replace $CIRCLE_TAG ./releases
      - run:
          name: Publish CircleCI orb
          command: |
            CCI_VERSION=0.1.11540
            wget https://github.com/CircleCI-Public/circleci-cli/releases/download/v$CCI_VERSION/circleci-cli_$CCI_VERSION\_linux_amd64.tar.gz
            tar -xf circleci-cli_$CCI_VERSION\_linux_amd64.tar.gz
            mv circleci-cli_$CCI_VERSION\_linux_amd64 cli

            export CIRCLECI_CLI_TOKEN=$(vault kv get -field=circleci_token ES/harpocrates)
            CC_NAMESPACE=bestsellerit
            ORB_PATH=./orb/orb.yml
            ORB_NAME=secret-injector

            ./cli/circleci orb validate $ORB_PATH

            if [[ $CIRCLE_TAG == *"dev"* ]]; then
              ./cli/circleci orb publish $ORB_PATH $CC_NAMESPACE/$ORB_NAME@dev:$CIRCLE_TAG
            else
              ./cli/circleci orb publish $ORB_PATH $CC_NAMESPACE/$ORB_NAME@$CIRCLE_TAG
            fi

test_filter: &test_filter
  filters:
    tags:
      ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/

release_filter: &release_filter
  filters:
    tags:
      only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
    branches:
      ignore: /.*/

common_context: &common_context
  context: 
    - es02-prod
    - shared

workflows:
  test:
    jobs:
      - secret-injector/dump-secrets:
          name: secrets-common
          <<: *common_context
          <<: *test_filter
      - secret-injector/dump-secrets:
          name: secrets-app
          vault-path: ES/data/service_accounts/harbor/harpocrates-ci
          requires:
            - secrets-common
          <<: *common_context
          <<: *test_filter
      - test:
          <<: *common_context
          <<: *test_filter
      - test-sonar:
          requires:
            - secrets-app
          <<: *common_context
          <<: *test_filter
      - build-go:
          requires:
            - secrets-app
          <<: *common_context
          <<: *test_filter
      - docker-build:
          requires:
            - build-go
          <<: *common_context
          <<: *test_filter

  test-build:
    jobs:
      - secret-injector/dump-secrets:
          name: secrets-common
          <<: *common_context
          <<: *release_filter
      - secret-injector/dump-secrets:
          name: secrets-app
          vault-path: ES/data/service_accounts/harbor/harpocrates-ci
          requires:
            - secrets-common
          <<: *common_context
          <<: *release_filter
      - test:
          <<: *common_context
          <<: *release_filter
      - build-go:
          requires:
            - secrets-app
          <<: *common_context
          <<: *release_filter
      - docker-build-n-push:
          requires:
            - build-go
          <<: *common_context
          <<: *release_filter
      - publish:
          requires:
            - docker-build-n-push
          <<: *common_context
          <<: *release_filter
