apiVersion: batch/v1
kind: CronJob
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: secret-dumper
              image: harbor.bestsellerit.com/library/harpocrates:$HARPOCRATES_VERSION
              args:
                - '$SECRETS'
              volumeMounts:
                - name: secrets
                  mountPath: /secrets
              env:
                - name: VAULT_ADDR
                  value: $VAULT_ADDR
                - name: AUTH_NAME
                  value: $AUTH_NAME
                - name: ROLE_NAME
                  value: $ROLE_NAME
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false


          containers:
            - name: $CONTAINER_NAME
              volumeMounts:
                - name: secrets
                  mountPath: /secrets
          volumes:
            - name: secrets
              emptyDir: {}
