apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: $APP_NAME
  namespace: $NAMESPACE
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: secret-dumper
              image: harbor.bestsellerit.com/library/harpocrates:$HARPOCRATES_VERSION
              args:
                - '$SECRETS'
              volumeMounts:
                - name: secrets
                  mountPath: /secrets
              env:
                - name: VAULT_ADDR
                  value: $VAULT_ADDR
                - name: CLUSTER_NAME
                  value: $CLUSTER_NAME

          containers:
            - name: $CONTAINER_NAME
              volumeMounts:
                - name: secrets
                  mountPath: /secrets
          volumes:
            - name: secrets
              emptyDir: {}
