apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  template:
    spec:
      initContainers:
        - name: secret-dumper
          image: harbor.bestsellerit.com/library/harpocrates:$HARPOCRATES_VERSION
          args:
            - '$SECRETS'
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: VAULT_ADDRESS
              value: $VAULT_ADDR
            - name: CLUSTER_NAME
              value: $CLUSTER_NAME
          
      containers:
      - name: $APP_NAME
        volumeMounts:
          - name: secrets
            mountPath: /secrets
      volumes:
        - name: secrets
          emptyDir: {}