apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $APP_NAME
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
spec:
  template:
    metadata:
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      initContainers:
        - name: secret-dumper
          image: harbor.bestsellerit.com/library/harpocrates:$HARPOCRATES_VERSION
          args:
            - '$SECRETS'
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: HARPOCRATES_VAULT_ADDRESS
              value: $VAULT_ADDR
            - name: HARPOCRATES_CLUSTER_NAME
              value: $CLUSTER_NAME
          
      containers:
      - name: $APP_NAME
        volumeMounts:
          - name: secrets
            mountPath: /secrets
      volumes:
        - name: secrets
          emptyDir: {}