name: goreleaser

on:
  release:
    types: [published]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Getting secrets
        id: secrets
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          method: jwt
          url: ${{ vars.VAULT_ADDR }}
          path: ${{ vars.VAULT_AUTH_PATH }}
          role: ${{ vars.VAULT_ROLE }}
          exportToken: true
          secrets: |
            SHARED/data/common artifact_registry_url | ARTIFACT_REGISTRY_URL ;
            SHARED/data/common artifact_registry_project | ARTIFACT_REGISTRY_PROJECT ;
            PLATFORM/data/harpocrates/prod GITHUB_APP_ID | GITHUB_APP_ID ;
            PLATFORM/data/harpocrates/prod GITHUB_APP_PRIVATE_KEY | GITHUB_APP_PRIVATE_KEY ;

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ steps.secrets.outputs.GITHUB_APP_ID }}
          private-key: ${{ steps.secrets.outputs.GITHUB_APP_PRIVATE_KEY }}

      - id: "auth"
        name: Auth GCloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_POOL_PROVIDER_NAME }}
          service_account: ${{ vars.WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "go.mod"

      - name: "Configure docker"
        run: "gcloud auth configure-docker ${{ steps.secrets.outputs.ARTIFACT_REGISTRY_URL }}"

      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          # A GitHub App token is used here because pushing to other repositories
          # (like BESTSELLER/homebrew-tap and BESTSELLER/winget-pkgs) requires cross-repo write access.
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          IMAGE_NAME: "${{ steps.secrets.outputs.ARTIFACT_REGISTRY_URL }}/${{ steps.secrets.outputs.ARTIFACT_REGISTRY_PROJECT }}/public-docker/${{ github.event.repository.name }}"
